#spring.datasource.url: jdbc:mysql://localhost:3306/spring_jpa
#spring.datasource.username: root
#spring.datasource.password: Password1
spring:
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/spring_jpa
    username: root
    password: Password1
  flyway:
    locations: classpath:/db/migration/mysql/complete,classpath:/db/migration/mysql/devdata