# Spring jpa configuration
# https://medium.com/@jonashavers/how-to-create-database-test-data-for-spring-boot-applications-with-flyway-db-294a436db7ee

spring:
  application:
    name: kotlin-meets-springboota

  profiles:
    active: dev